### ISSUE TITLE
Add iscc command line options support

### ISSUE THREAD

**Issue by zergius-eggstream** [dustinblackman/gulp-inno#3]
Inno Setup command line compiler has some useful options, signing tools for example.
Please add support for those options, using optional config object. You already have unused argument `opts` in your export function.
It may be used somewhat like
`opts = opts || {};` and `args = [opts.compilerOptions, script_path];` in index.js
somewhat like
`.pipe(inno({compilerOptions: '/SkSign=' + signPath + ' /f ' + certificatePath + ' /p yourpfxpass $p'}))` in gulpfile.js
and 
`SignTool=kSign /d $qYOUR_DESCRIPTION$q /du $qhttp://www.example.com$q $f` in [Setup] section of install.iss
[index.txt](https://github.com/dustinblackman/gulp-inno/files/223581/index.txt)

**Comment by dustinblackman** [comment]
I'll see if I can get to it this week. PRs are welcome!

**Comment by vidhu** [comment]
Implemented in #4
